### ISSUE TITLE
WE_ItemBox is unusable, making mod unusable

### ISSUE THREAD

**Issue by Koyoss** [Silverfeelin/Starbound-WEdit#12]
http://prntscr.com/cf1f8y The itembox(gotten through crafting- the one that you spawn isn't working either. ) can't be used- I try to use it, but it doesn't give me anything.  Possibly a bug due to it being sorted to that menu in the inventory? I'm unsure.

**Comment by Silverfeelin** [comment]
The item tab used is intentional; I found it the least intrusive tab for a bunch of items to be added to.

To get the items, make sure you have the dash tech activated on your character and that you are using the item *outside* of your inventory. The easiest way to do the latter is to drag the item on your hotbar, then using the item from there.
Make sure you don't have any other mods installed that might modify the dash tech, since they might be overwriting certain parts of this mod.

**Comment by Silverfeelin** [comment]
Closed as no status update was given. Assuming user error was made, as the issue could not be recreated after setting everything up.
