### ISSUE TITLE
WE_itembox doesnt work

### ISSUE THREAD

**Issue by carminaburana123** [Silverfeelin/Starbound-WEdit#14]
After I Equip the box it doesn't do anything. 
Lets get more into detail:
I equipped the box in spot 1-6 and tried left or right click, no items given
I pressed 'x' to get to the other item bar and tried it again, no succes. 
Next up was the command: 

    /spawnitem triangliumore 1 '{"itemTags":[], "radioMessagesOnPickup":[], "learnBlueprintsOnPickup":[], "twoHanded":true, "shortdescription":"WE_ItemBox", "category":"^orange;WEdit: Item Box", "description":"^yellow;^yellow;Primary Fire: Spawn Tools.^reset;", "inventoryIcon":"/objects/floran/chestfloran1/chestfloran1icon.png"}'

There is a small difference in the icon of the chest. without the spawn command it looks like a carbord box, with the command it looks like a treasure chest. But no functionality what so ever.
Quitted and rejoined the game, and did previous again, nothing. 
So i went to restarting the game, same problem
Next step was relaunching without the mod, i deleted the mod, relaunched the game played a while..., and then i closed it again. 

Now i tried redownloading it. Tried everything again, and still no response. 

However i used the mod before and it worked fine

**Comment by carminaburana123** [comment]
Ok i think i don't have the dash tech on. Could that really be the reason. It really looks like a bug to me. I will try it in the next 20 min and give some feedback

**Comment by carminaburana123** [comment]
That was indeed the problem. Is there a reason why dash must be activated?

**Comment by Silverfeelin** [comment]
Covered by the first paragraph of the [Usage](https://github.com/Silverfeelin/Starbound-WEdit/wiki/Usage) section.

---

Multiple methods to work around this "issue" while keeping the item multiplayer friendly, here's two and the reason I didn't choose for them:

* Recipes for (custom) items are potentially dangerous. They work fine, but they are all fully stored inside your player file and persist even after uninstalling the mod. WEdit has quite a few tools, and each tool is very large compared to the average item due to the custom icons.
Storing all of these in your player file (and new ones every time a tool is updated) can cause issues down the road for players. This has happened before as a result of people using a bunch of other mods with custom items.
Specifically, it can break external inventory editors like StarCheat.

* Storing all tool data inside the toolbox simply results in your game lagging; there'd be too much data in one item. It also means that your toolbox would spawn invalid items when the mod is updated.

Instead of these methods, the toolbox spawns items from a configuration file. To achieve this, a script (the tech script) has to read the file once the item is activated. This results in up-to-date items being spawned, and the item data is only present in the newly spawned items. Although you still need to replace older tools with newer ones, you don't need to create a new toolbox (unless you've destroyed the previous one).

PS. The difference in icons is another result of the above mentioned issue related to recipes. The recipe holds an existing texture (treasure chest) rather than the custom box from Fugue Icons. I've done this to keep the amount of data stored to a minimum.
