### ISSUE TITLE
Crash on startup with WEdit installed

### ISSUE THREAD

**Issue by FireStorm-Gaming** [Silverfeelin/Starbound-WEdit#23]
https://hastebin.com/epurexuban.sql

**Comment by Silverfeelin** [comment]
I'm assuming you are CaptainKyros, or are relaying the information.

The issue doesn't seem to be with WEdit itself, but with Steam/Windows. WEdit was updated on Steam to use the 1.3.2 pak, rather than the folder based 1.3.1. Steam should be updating the mod properly (removing the WEdit folder and replacing it with WEdit.pak), but hasn't in this situation.

My solution is to unsubscribe from the mod and to delete the mod folder (`734859295`) before resubscribing, as that would force Steam to only obtain the latest version of the mod.

**Comment by Silverfeelin** [comment]
Closed due to lack of response.
