### ISSUE TITLE
Noclip not working.

### ISSUE THREAD

**Issue by PandyRitchford** [Silverfeelin/Starbound-WEdit#29]
Hello. I downloaded the steam version of this mod from the workshop and i tried to use the noclip feature but it doesnt work. Ive changed the binding of it to different keys besides "g", but it doesnt work. Ive reinstalled the mod three times. Any help appreciated. Thanks.

**Comment by Silverfeelin** [comment]
Could you set it to "up down" in the WEdit settings? You'll be able to toggle noclip by pressing W/S at the same time.
If this also doesn't work you either have a conflicting mod or the mod shouldn't work altogether due to an error (which is logged to your `starbound.log`). If this does work then you've simply configured things wrong (i.e. by not setting the key to "g" in both your in-game controls as well as the WEdit settings).

This page will help you get to the WEdit settings:
https://github.com/Silverfeelin/Starbound-WEdit/wiki/Settings-Interface

**Comment by Silverfeelin** [comment]
Closed as there has been no response for a long time now. If you're still having issues you're free to leave a new comment with more details.

**Comment by thakyZ** [comment]
I know for a fact that this happens when the player has any frackin' universe body tech equipped. But I am not sure if this is their issue.
